---
# tasks file for bootstrap
- name: wait for system
  wait_for:
    port: "{{ ansible_port | default('22') }}"
    host: "{{ (ansible_ssh_host | default(ansible_host) | default(inventory_hostname)) }}"
  connection: local
  become: no
  when:
    - ansible_connection is defined
    - ansible_connection != "docker"
    - bootstrap_wait_for_host

- name: bootstrap system
  block:
    - name: test connection to system
      wait_for_connection:
        timeout: "{{ bootstrap_timeout }}"
      register: bootstrap_connect
      changed_when: no
      become: no

  rescue:
    - name: import discover.yml
      include: discover.yml

    - name: flush handlers
      meta: flush_handlers

- name: gather facts
  setup:

- name: add community repository for alpine
  lineinfile:
    path: /etc/apk/repositories
    line: "{{ bootstrap_alpine_community_repo }}"
  when:
    - ansible_distribution == "Alpine"

- name: install software to support stable modules
  package:
    name: "{{ bootstrap_stable_packages }}"
    state: present
  when:
    - bootstrap_stable_packages is defined
  register: packagestableresult
  until: packagestableresult is succeeded
  notify: gather facts

- name: install software to support preview modules
  package:
    name: "{{ bootstrap_preview_packages }}"
    state: present
  when:
    - bootstrap_preview
    - bootstrap_preview_packages is defined
  register: packagepreviewresult
  until: packagepreviewresult is succeeded
  notify:
    - gather facts
